/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {

  ug1Sidebar: [{ type: 'autogenerated', dirName: 'ug1' }],

  ug2Sidebar: [{ type: 'autogenerated', dirName: 'ug2' }],
  
  mw05Sidebar: [{ type: 'category', label: 'Most Wanted (2005)', link: { type: 'doc', id: 'mw05/index' }, collapsed: true, collapsible: true,
    items: [
      { type: 'doc', id: 'mw05/setup', label: 'Setting up for speedruns' },
      { type: 'doc', id: 'mw05/general', label: 'General information' },
      { type: 'doc', id: 'mw05/simple-any', label: 'Simple Career Any% guide' },
      { type: 'doc', id: 'mw05/inter-any', label: 'Intermediate Career Any% guide' },
      { type: 'doc', id: 'mw05/info' , label: 'Advanced information' },
      { type: 'doc', id: 'mw05/expert-any', label: 'Expert Career Any% route' }, ], },
        
  {type: 'link', label: 'Speedrun.com', href: 'https://www.speedrun.com/nfsmw05',},
  {type: 'link', label: 'Category Extensions', href: 'https://www.speedrun.com/nfsmw05_ce',},
  {type: 'link', label: 'Extreme Most Wanted Racers', href: 'https://extrememostwantedracers.weebly.com/',}],

  cSidebar: [{ type: 'autogenerated', dirName: 'c' }],

  psSidebar: [{ type: 'autogenerated', dirName: 'ps' }],

  ucSidebar: [{ type: 'autogenerated', dirName: 'uc' }],

  trSidebar: [{ type: 'autogenerated', dirName: 'tr' }],

};

export default sidebars;
